-- sudo mysql < bootstrap.sql

CREATE DATABASE IF NOT EXISTS COP4331;

CREATE USER IF NOT EXISTS 'TheBeast'@'%' IDENTIFIED BY 'CHANGE_ME';
GRANT ALL PRIVILEGES ON COP4331.* TO 'TheBeast'@'%';
CREATE USER IF NOT EXISTS 'TheBeast'@'localhost' IDENTIFIED BY 'CHANGE_ME';
GRANT ALL PRIVILEGES ON COP4331.* TO 'TheBeast'@'localhost';
FLUSH PRIVILEGES;
